networks:
  vehicle-network:
    name: vehicle-network
    driver: bridge
    #external: false
services:

  app:
    build: .
    container_name: vehicle-management-service

    ports:
      - "${PORT}:${PORT}"

    volumes:
      - .:/app

    env_file:
      - .env

    depends_on:
      - postgres

    networks:
      - vehicle-network

  postgres:
    image: postgres:17

    container_name: vehicle-management-db

    restart: always

    environment:
      POSTGRES_DB: vehicle_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - vehicle_management_postgres_data:/var/lib/postgresql/data

    networks:
      - vehicle-network

volumes:
  vehicle_management_postgres_data:
