apiVersion: v1
kind: Service

metadata:
  name: vehicle-management-service

spec:
  type: NodePort

  selector:
    app: vehicle-management-service

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080